# Generated by Django 3.2.4 on 2021-06-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
